chore(taro): migrate configure to taro@4
zjutjh/WeJH-Taro pull request #124
Opened 2024-10-13 07:20 UTC by j10ccc

Update deps and configure, use Vite as build tool.

2024-10-14 14:24 UTC, j10ccc commented
## 破坏性更新

1. 环境变量的变量名修改，并区分构建时和运行时，具体见 `.env.sample`
2. vite 对静态资源引用的方式更新，在 vue 文件和 sass 文件中都有变化
4. 小程序 AppId 的设置方式有变化，从显式声明在 `project.config.js` 改成从环境变量 `TARO_APP_ID` 读取，具体见 [Taro 文档](https://nervjs.github.io/taro-docs/docs/env-mode-config/#特殊环境变量-taro_app_id)

2024-10-21 05:11 UTC, xixiIBN5100 requested changes
<img width="1178" alt="5194553d34a15bf13fbec1359fd352d7" src="https://github.com/user-attachments/assets/76b57128-6572-4f8b-91ef-d8e439494fd2">
构建warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

2024-10-22 06:50 UTC, j10ccc commented
> <img alt="5194553d34a15bf13fbec1359fd352d7" width="1178" src="https://private-user-images.githubusercontent.com/144224541/378280638-76b57128-6572-4f8b-91ef-d8e439494fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjI3MjgsIm5iZiI6MTcyOTUyMjQyOCwicGF0aCI6Ii8xNDQyMjQ1NDEvMzc4MjgwNjM4LTc2YjU3MTI4LTY1NzItNGY4Yi05MWVmLWQ4ZTQzOTQ5NGZkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNDUzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWI4YTgwM2NjOTU5MzQ1YmQ2YmY4YTg5NTkwZDkwODRkNzJkYTcxYjc3ZGIyMzE5YmU3NWQwMmUwNTJjNGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9hzVcxCLE3S2CKtqX2SxGoaMoBO59iYyBuEVpSagb8M"> 构建warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

项目里面还有些 Dart-Sass 2.0.0 的 Deprecated 警告，这些忽略就行了。毕竟我们锁了 `sass` 的 minor 版本。如果未来可以修看这个 issue，https://github.com/vitejs/vite/issues/14689#issuecomment-2095118836。

taro 没有留文档说明要如何透传配置给 vite，同时也不知道 css 文件到底是不是 vite 用 postcss 处理的。现在处理不了这个问题。

2024-10-23 06:26 UTC, xixiIBN5100 approved these changes

2024-10-24 09:59 UTC, merged