feat(theme): 新增2024毅行主题
zjutjh/WeJH-Taro pull request #129
Opened 2024-10-16 07:18 UTC by xixiIBN5100

2024-10-16 07:19 UTC, xixiIBN5100 commented
这个背景图质量不太好,可能会用原图上图床,等晚上发布

2024-10-19 03:23 UTC, j10ccc commented
AppList 那几个 icon 也是主题限定的？

2024-10-19 03:35 UTC, j10ccc requested changes

2024-10-19 03:35 UTC, j10ccc commented on src/style/darkmode/light.scss
> -  --wjh-color-pink-700: #{$pink-700};
到底是删除紫色主题还是粉色主题？

2024-10-19 03:35 UTC, j10ccc commented on src/components/ThemeConfig/index.vue
> +    return "--wjh-color-background-page: #fefefel; --wjh-color-background-container: #FAFAFAFF";
你确定这里加上 `--wjh-color-background-container` 就能解决问题了？`light` 这个 classname 下本来就有声明这个变量，你这加了相当于白加。试过了没问题？

2024-10-19 03:37 UTC, j10ccc commented on src/style/darkmode/light.scss
> -  --wjh-color-pink-700: #{$pink-700};
还有你这个删除了，`src/style/variables/color.scss` 里面的 sass 变量你不删掉？

2024-10-19 06:16 UTC, j10ccc commented
主题这个页面，页面路由还是 lab 啊，路由和文件名有关，这个得改了

2024-10-19 14:23 UTC, j10ccc commented
这个页面组件 src/pages/lab/index.vue 里面，给 `theme-config` 传了一个 class，完全没必要，给他删了

2024-10-20 08:38 UTC, j10ccc approved these changes

2024-10-20 17:02 UTC, merged