fix(input): fix password input content can be seen
zjutjh/WeJH-Taro pull request #148
Opened 2024-11-02 14:21 UTC by xixiIBN5100

2024-11-02 14:23 UTC, xixiIBN5100 commented on src/pages/setting/changePassword/index.vue
> +  if (password.value === "" || passwordAgain.value === "") return;
这里是防止第一次输入**密码**但是没有输入**确认密码**时触发校验

2024-11-02 14:26 UTC, xixiIBN5100 commented on src/pages/setting/changePassword/index.vue
> +  if (password.value === "" || passwordAgain.value === "") return;
当确认密码和密码为空的时候不改变校验状态在交互上感觉也合理一些

2024-11-02 14:29 UTC, j10ccc requested changes

2024-11-02 14:29 UTC, j10ccc commented on src/pages/setting/changePassword/index.vue
> +              @blur="formCheck"
如果聚焦的情况下，点击了“确认修改” 按钮，是不是会跳过失焦事件？check 的步骤最好在提交按钮上也做一个

2024-11-03 02:23 UTC, j10ccc requested changes

2024-11-03 02:23 UTC, j10ccc commented on src/pages/setting/changePassword/index.vue
> +  }
你单独写个函数 `handleConfirm`，里面调用 `formCheck` 就行了，没必要用 `clickButton` 耦合两种情况

2024-11-03 04:58 UTC, j10ccc approved these changes

2024-11-03 05:16 UTC, merged