Info
zjutjh/WeJH-Taro pull request #56
Opened 2023-08-05 16:11 UTC by Tong030905

2023-08-06 01:10 UTC, j10ccc commented
你把 #55 关了干啥？提到的问题你也没改完啊

2023-08-06 01:13 UTC, j10ccc commented
校园资讯是确定了 **专门做给 for you** 发通知的是吗？

2023-08-09 15:00 UTC, j10ccc reviewed
我给你一个方案，你把 `Information` 的类型改了（这样子可能还要改 API），改成

```ts
interface Information {
  // ...other properties
  publisher: {
    name: string;
    backgroundImageUrl: string;
  }
}
```


背景图片是和发布者有直接关系的，而不是和一条推文有关，你写在这个组件里面是不合理的。这个关系应该是数据库控制的，而不是前端在代码里面绑定他们的关系。

这次给你留 Comment，你们对这种逻辑不关心的话就可以直接合并了 @Tianci-King

2023-08-09 15:01 UTC, Tong030905 commented on src/pages/announcement/InformationCard/index.vue
> +  <card :class="{ [styles.container]: props.source.publisher === Author }">
好的 谢谢孙哥 我收到了

2023-08-10 13:50 UTC, Tong030905 commented
新增了详情查询页面

2023-08-10 16:25 UTC, j10ccc commented on src/store/service/information.ts
>  }
这个单独的 information 有什么用，需要做好注释

2023-08-11 17:20 UTC, Tong030905 commented on src/store/service/information.ts
>  }
那这样的话，store里的information就可以删除了吗

2023-08-12 03:26 UTC, j10ccc commented on src/store/service/information.ts
>  }
是的

2023-08-12 09:02 UTC, j10ccc requested changes

2023-08-12 09:02 UTC, j10ccc commented on src/pages/information/index.vue
> +const information = informationList.value.find((information) => information.id == informationId);
这里应该是 `information` 是计算属性吧？List 是计算中间值，怎么他是计算属性，`information` 反而不是？

2023-08-12 12:11 UTC, j10ccc commented
`informationList` 其他地方也用不到，直接就一个计算属性好了，store 里面拿出来的也不用 reverse 了

2023-08-12 14:46 UTC, j10ccc commented
🥹，`find` 一下不会改 store 里面的值，就不需要额外解构了

2023-08-12 14:47 UTC, Tong030905 commented
> 🥹，`find` 一下不会改 store 里面的值，就不需要额外解构了

🥹🤪

2023-08-12 14:52 UTC, j10ccc approved these changes

2023-08-12 14:55 UTC, j10ccc commented
你看看两个 `project.config.json` 你这边能不能别提交上来

2023-08-12 14:56 UTC, Tong030905 commented
> 你看看两个 `project.config.json` 你这边能不能别提交上来

啊 我最近都只是提交src文档 这俩文件还被修改了吗🥹🥺

2023-08-12 14:58 UTC, j10ccc commented
> > 你看看两个 `project.config.json` 你这边能不能别提交上来
> 
> 啊 我最近都只是提交src文档 这俩文件还被修改了吗🥹🥺

这个 pr 对应的好几个 commit，你之前改的。你再发个 commit 改回来应该就行了

2023-08-12 14:59 UTC, Tong030905 commented
> > > 你看看两个 `project.config.json` 你这边能不能别提交上来
> > 
> > 
> > 啊 我最近都只是提交src文档 这俩文件还被修改了吗🥹🥺
> 
> 这个 pr 对应的好几个 commit，你之前改的。你再发个 commit 改回来应该就行了

🫡

2023-08-12 15:03 UTC, Tong030905 commented
> > > 你看看两个 `project.config.json` 你这边能不能别提交上来
> > 
> > 
> > 啊 我最近都只是提交src文档 这俩文件还被修改了吗🥹🥺
> 
> 这个 pr 对应的好几个 commit，你之前改的。你再发个 commit 改回来应该就行了

这下 是不是真的拿捏了 🥲

2023-08-12 15:05 UTC, j10ccc commented
pr 的 title 你改一下，有些时候合并用 squash，要重新写 commit message 的

2023-08-12 15:10 UTC, Tong030905 commented
> pr 的 title 你改一下，有些时候合并用 squash，要重新写 commit message 的

没太明白，是改成squash？还是要改成什么🤔

2023-08-12 15:13 UTC, j10ccc commented
> > pr 的 title 你改一下，有些时候合并用 squash，要重新写 commit message 的
> 
> 没太明白，是改成squash？还是要改成什么🤔

squash 是合并的一种方式，就是把所有 commit 合成一条新的。所以要写 commit message，内容是总结 pr 干了什么。pr  干了什么应该用一句话在 title 描述，你发 pr 的时候没注意。合并之前你先把 title 改了

2023-08-12 15:24 UTC, j10ccc commented
> 你可以在自己仓库里面试一下 pr 的合并，比较 merge 和 squash 的区别

你这 pr 里面 commit 改糊了，美观起见我选择用 squash。squash 有个坏处就是所有细节没了，如果有多个开发者，那每个开发者干了什么也不知道了。所以尽量 commit 写规范，不重要的代码修改合并在重要的 commit 里面，你在自己的仓库处理好。

你这个 pr 就是后面写的代码有点小问题，应该自己在本地 rebase 改好再 force push 上来的。如果这样用 merge 是最好的（pr 中所有 commit 保留，同时会追加一条 merge commit），这次方便起见我直接在网页上 squash 了。

@Tianci-King 合并的时候注意这些

2023-08-12 15:26 UTC, merged

2023-08-12 15:29 UTC, j10ccc commented
还有 pr 的标题和 issue 的标题没有格式一说，把内容描述一句话概括就行了，详细的描述写在 message body 里面（发pr 的时候应该有个大 textarea）